### ISSUE TITLE
source.sourceAndMap is not a function

### ISSUE THREAD

**Issue by windsonR** [hzsrc/webpack-theme-color-replacer#118]
在`@vue/cli`中配置换肤插件,并执行build

如果启用了webpack5的持久化缓存,那么在第二次build(第一次可以正常执行)的时候就会出现`source.sourceAndMap is not a function`

如果禁用持久化缓存或者使用插件的`injectToHtml`配置都可以正常执行,不会出现报错

[repo](https://github.com/windsonR/webpack-theme-demo.git)

可以使用`repo`进行测试,在第二次build的时候就会报错.

```
hello-world git:(main) yarn build
yarn run v1.22.19
$ vue-cli-service build
All browser targets in the browserslist configuration have supported ES module.
Therefore we don't build two separate bundles for differential loading.


⠸  Building for production...Extracted theme color css content length: 21
<w> [webpack.cache.PackFileCacheStrategy] Restoring failed for TerserWebpackPlugin|js/chunk-vendors.833c56b9.js from pack: TypeError: item.updateHash is not a function
 ERROR  HookWebpackError: source.sourceAndMap is not a function
HookWebpackError: source.sourceAndMap is not a function
    at makeWebpackError (/Users/user/hello-world/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /Users/user/hello-world/node_modules/webpack/lib/Compilation.js:3060:12
    at eval (eval at create (/Users/user/hello-world/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:54:1)
-- inner error --
TypeError: source.sourceAndMap is not a function
    at module.exports (/Users/user/hello-world/node_modules/webpack-sources/lib/helpers/streamChunks.js:15:31)
    at ConcatSource.streamChunks (/Users/user/hello-world/node_modules/webpack-sources/lib/ConcatSource.js:113:55)
    at exports.getSourceAndMap (/Users/user/hello-world/node_modules/webpack-sources/lib/helpers/getFromStreamChunks.js:17:33)
    at ConcatSource.sourceAndMap (/Users/user/hello-world/node_modules/webpack-sources/lib/ConcatSource.js:95:10)
    at CachedSource.sourceAndMap (/Users/user/hello-world/node_modules/webpack-sources/lib/CachedSource.js:169:41)
    at /Users/user/hello-world/node_modules/terser-webpack-plugin/dist/index.js:454:27
    at next (/Users/user/hello-world/node_modules/terser-webpack-plugin/dist/utils.js:81:7)
    at onFulfilled (/Users/user/hello-world/node_modules/terser-webpack-plugin/dist/utils.js:78:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by windsonR** [comment]
https://github.com/hzsrc/webpack-theme-color-replacer/blob/1dae36eb5918f8705e6cc4cf25aadd1c04cf9878/src/Handler.js#L114

似乎就是这里的问题,_source在这里是个function,然后concat之后到webpack内部处理的时候就作为function来处理了

但是这里应该是一个String或者CachedSource.

直接在这里传入assetSource或者assetSource._source()或者assetSource.source()都可以编译成功.

**Comment by hzsrc** [comment]
你好！我这不好重现，你可以改一下Handler.js，然后再测试下吗？如果测试没问题可以拉一个分支提交PR

**Comment by windsonR** [comment]
提交了个PR,只对assetSource._source的类型进行了下判断,如果是function,那么就执行它.对于其他的代码应该不会造成影响.
