### ISSUE TITLE
node18报错，replaceFileName.js

### ISSUE THREAD

**Issue by yohayo** [hzsrc/webpack-theme-color-replacer#126]
建议replaceFileName.js中修改crypto.createHash方法参数
`yarn run v1.22.19
$ vue-cli-service serve --mode development
 INFO  Starting development server...
[92%] sealing (asset processing ThemeColorReplacer)
Extracted theme color css content length: 26565
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at getHash (\node_modules\webpack-theme-color-replacer\src\replaceFileName.js:17:21)
    at replaceFileName (\node_modules\webpack-theme-color-replacer\src\replaceFileName.js:10:68)     
    at getFileName (\node_modules\webpack-theme-color-replacer\src\Handler.js:57:40)
    at Handler.handle (\node_modules\webpack-theme-color-replacer\src\Handler.js:41:26)
    at \node_modules\webpack-theme-color-replacer\src\index.js:37:38
    at fn (\node_modules\webpack\lib\Compilation.js:510:9)
    at _next2 (eval at create (\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:48:1)
    at eval (eval at create (\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:69:1)  
    at \node_modules\webpack\lib\Compilation.js:522:10
    at \node_modules\html-webpack-plugin\lib\cached-child-compiler.js:267:53 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by hzsrc** [comment]
尝试这个办法：
https://blog.csdn.net/chy555chy/article/details/128481013
后面我看看有没有更好的方案。

**Comment by FlyingTigerReally** [comment]
@hzsrc 可以修复这个问题吗？项目从webpack4升级到webpack5后出现digital envelope routines::unsupported。

**Comment by MinatoHikari** [comment]
@hzsrc 有进展吗

**Comment by hzsrc** [comment]
是nodejs 18不支持md4 hash算法所致，请更新至1.5.1版本（改用md5）。或者更新nodejs
